### ISSUE TITLE
Variable with binary outcome cannot be chosen in 2x2 mosaic plot

### ISSUE THREAD

**Issue by aaronwlsong** [VEuPathDB/web-eda#1453]
In MORDOR study, the var study arm has two values, but it cannot be chosen in 2x2 mosaic, however, if I plot it in RxC mosaic plot meanwhile keep all other things the same, it works. 

In 2x2 mosaic, I cannot choose var:"study arm" for either x or y axis.
<img width="922" alt="Screen Shot 2022-10-26 at 5 11 38 PM" src="https://user-images.githubusercontent.com/61077845/198142994-acf78908-4dac-4046-bc51-63f5315613cb.png">

In RXC mosaic, it works. 

<img width="889" alt="Screen Shot 2022-10-26 at 5 30 32 PM" src="https://user-images.githubusercontent.com/61077845/198143181-c7b178aa-343b-48ea-b37c-fc52993e77cb.png">

**Comment by dmfalke** [comment]
@d-callan I suspect the backend hasn't been udpated and/or tagged for the related changes. Can you confirm?

**Comment by dmfalke** [comment]
I tried to update eda-data to v3.2.1, but got an error, so reverted back to v3.2.0

**Comment by d-callan** [comment]
3.2.1 is the version w these changes. What was the error?

**Comment by dmfalke** [comment]
I lost it and forgot to copy it. It was something about a method `setMinValues` (or something like that).

**Comment by dmfalke** [comment]
For posterity

```
^[[m^[[33m2022-11-04 15:38:39.231 [rid:1ClTl] WARN  ErrorMapper:79 - Caught Exception:
^[[m java.lang.NoSuchMethodError: 'void org.veupathdb.service.eda.common.plugin.constraint.VisualizationDataElement.setMinNumValues(java.lang.Number)'
        at org.veupathdb.service.eda.common.plugin.constraint.VisualizationDataElement.<init>(VisualizationDataElement.java:22) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.common.plugin.constraint.ConstraintPattern.element(ConstraintPattern.java:14) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.ds.plugin.pass.HistogramPlugin.getConstraintSpec(HistogramPlugin.java:59) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.ds.metadata.AppsMetadata.viz(AppsMetadata.java:117) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.ds.metadata.AppsMetadata.<clinit>(AppsMetadata.java:47) ~[service.jar:3.0.0]
        at org.veupathdb.service.eda.ds.service.AppsService.getApps(AppsService.java:58) ~[service.jar:3.0.0]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) ~[service.jar:3.0.0]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[service.jar:3.0.0]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[service.jar:3.0.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[service.jar:3.0.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[service.jar:3.0.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[service.jar:3.0.0]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) ~[service.jar:3.0.0]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) ~[service.jar:3.0.0]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) ~[service.jar:3.0.0]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:190) ~[service.jar:3.0.0]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535) ~[service.jar:3.0.0]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515) ~[service.jar:3.0.0]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
^[[33m2022-11-04 15:38:39.240 [rid:1ClTl] WARN  RequestLogger:42 - Request end: GET /apps 500
```

**Comment by d-callan** [comment]
there was a deployment issue which should be resolved now @sweverschulman

**Comment by sweverschulman** [comment]
Can now produce the desired visualization. 

![Image](https://user-images.githubusercontent.com/62298921/200397049-09dc5d7b-4a12-40c1-8546-f8e9282a4642.png)
